apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - namespace.yaml
  - ./operator-oauth.yaml
  - ./tailscale-operator.yaml
  - ./cluster-issuer.yaml
  - ./operator-rbac.yaml
  - ./tailscale-auth-secret.yaml
