apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./operator-oauth.yaml
  - ./tailscale-operator.yaml
  - ./cluster-issuer.yaml
  - ./operator-rbac.yaml
