apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "39.x"
  interval: 1h
  install:
    crds: CreateReplace
  values:
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.0.31
        # Cilium L2: allow forwarding to any node (avoids drop when L2 lease and pod are on same node)
        externalTrafficPolicy: Cluster
      loadBalancerClass: io.cilium/l2-announcer
    ingressRoute:
      dashboard:
        enabled: true # Automatically creates the internal routing rule
        matchRule: Host(`traefik.joesabbagh.com`)
        entryPoints: ["web"]
    ports:
      web:
        port: 8000 # Internal container port (Unprivileged)
        exposedPort: 80 # External LoadBalancer port (What browser uses)
      websecure:
        port: 8443 # Internal container port (Unprivileged)
        exposedPort: 443 # External LoadBalancer port (What browser uses)
