apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - commafeed
  - homepage
  - jellyfin
  - linkding
  - metallb
  - n8n
  - pihole
  - tailscale
  - traefik
