$ANSIBLE_VAULT;1.1;AES256
35313665663866323463613461396163343363643861313238663465656330353162306130376235
3138633966346263303731373635336133656134376139360a633138353261363961323363363761
35633538303666373562353230356336303331323939636363303932383439313730306231646233
6262626432623839340a646561373635656334646539656436336539303935616632623631306566
64363266633737363531363330336330643835393539383562386638363962366434373866336533
31303564663630313832666466393763333838366230333336373131316263353036643238636139
393531623861376431396133366661666636
