apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./cert-manager-repo.yaml
  - ./cilium-repo.yaml
  - ./tailscale-repo.yaml
  - ./traefik-repo.yaml
